- job:
    name: openstack-health-nodejs10-run-lint
    parent: nodejs-run-lint
    description: |
      Run lint using Node 10.
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/openstack-health

- job:
    name: openstack-health-nodejs10-run-test-browser
    parent: nodejs-run-test-browser
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/openstack-health
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-health-nodejs10-run-lint
        - openstack-health-nodejs10-run-test-browser
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-health-nodejs10-run-lint
        - openstack-health-nodejs10-run-test-browser
